#!/bin/bash

stack exec -- add-entry $1

echo "export CURRENT_STACK_EXE_ENTRY=$1" > .curname

source .curname
./building

if type "gen-hie" > /dev/null 2>&1; then
    gen-hie > hie.yaml
else
    stack install implicit-hie
    gen-hie > hie.yaml
fi
